// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.27.2
// source: customer-service/proto/customer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Customer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_customer_service_proto_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_customer_service_proto_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_customer_service_proto_customer_proto_rawDescGZIP(), []int{0}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerRequest) Reset() {
	*x = CreateCustomerRequest{}
	mi := &file_customer_service_proto_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerRequest) ProtoMessage() {}

func (x *CreateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_service_proto_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customer_service_proto_customer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCustomerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateCustomerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type EditCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCustomerRequest) Reset() {
	*x = EditCustomerRequest{}
	mi := &file_customer_service_proto_customer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCustomerRequest) ProtoMessage() {}

func (x *EditCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_service_proto_customer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCustomerRequest.ProtoReflect.Descriptor instead.
func (*EditCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customer_service_proto_customer_proto_rawDescGZIP(), []int{2}
}

func (x *EditCustomerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditCustomerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerRequest) Reset() {
	*x = GetCustomerRequest{}
	mi := &file_customer_service_proto_customer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerRequest) ProtoMessage() {}

func (x *GetCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_service_proto_customer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customer_service_proto_customer_proto_rawDescGZIP(), []int{3}
}

func (x *GetCustomerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCustomerRequest) Reset() {
	*x = DeleteCustomerRequest{}
	mi := &file_customer_service_proto_customer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomerRequest) ProtoMessage() {}

func (x *DeleteCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_service_proto_customer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomerRequest.ProtoReflect.Descriptor instead.
func (*DeleteCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customer_service_proto_customer_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCustomerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerResponse) Reset() {
	*x = CustomerResponse{}
	mi := &file_customer_service_proto_customer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerResponse) ProtoMessage() {}

func (x *CustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_service_proto_customer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerResponse.ProtoReflect.Descriptor instead.
func (*CustomerResponse) Descriptor() ([]byte, []int) {
	return file_customer_service_proto_customer_proto_rawDescGZIP(), []int{5}
}

func (x *CustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *CustomerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MessageOnlyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOnlyResponse) Reset() {
	*x = MessageOnlyResponse{}
	mi := &file_customer_service_proto_customer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOnlyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOnlyResponse) ProtoMessage() {}

func (x *MessageOnlyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_service_proto_customer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOnlyResponse.ProtoReflect.Descriptor instead.
func (*MessageOnlyResponse) Descriptor() ([]byte, []int) {
	return file_customer_service_proto_customer_proto_rawDescGZIP(), []int{6}
}

func (x *MessageOnlyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UploadCSVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"` // The entire CSV file
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`                          // Optional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadCSVRequest) Reset() {
	*x = UploadCSVRequest{}
	mi := &file_customer_service_proto_customer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadCSVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCSVRequest) ProtoMessage() {}

func (x *UploadCSVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_service_proto_customer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCSVRequest.ProtoReflect.Descriptor instead.
func (*UploadCSVRequest) Descriptor() ([]byte, []int) {
	return file_customer_service_proto_customer_proto_rawDescGZIP(), []int{7}
}

func (x *UploadCSVRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *UploadCSVRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UploadCSVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowsProcessed int32                  `protobuf:"varint,1,opt,name=rows_processed,json=rowsProcessed,proto3" json:"rows_processed,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadCSVResponse) Reset() {
	*x = UploadCSVResponse{}
	mi := &file_customer_service_proto_customer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadCSVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCSVResponse) ProtoMessage() {}

func (x *UploadCSVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_service_proto_customer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCSVResponse.ProtoReflect.Descriptor instead.
func (*UploadCSVResponse) Descriptor() ([]byte, []int) {
	return file_customer_service_proto_customer_proto_rawDescGZIP(), []int{8}
}

func (x *UploadCSVResponse) GetRowsProcessed() int32 {
	if x != nil {
		return x.RowsProcessed
	}
	return 0
}

func (x *UploadCSVResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_customer_service_proto_customer_proto protoreflect.FileDescriptor

const file_customer_service_proto_customer_proto_rawDesc = "" +
	"\n" +
	"%customer-service/proto/customer.proto\x12\bcustomer\"D\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"Q\n" +
	"\x15CreateCustomerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"9\n" +
	"\x13EditCustomerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"$\n" +
	"\x12GetCustomerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15DeleteCustomerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\\\n" +
	"\x10CustomerResponse\x12.\n" +
	"\bcustomer\x18\x01 \x01(\v2\x12.customer.CustomerR\bcustomer\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"/\n" +
	"\x13MessageOnlyResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"Q\n" +
	"\x10UploadCSVRequest\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"T\n" +
	"\x11UploadCSVResponse\x12%\n" +
	"\x0erows_processed\x18\x01 \x01(\x05R\rrowsProcessed\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x8e\x03\n" +
	"\x0fCustomerService\x12I\n" +
	"\fEditCustomer\x12\x1d.customer.EditCustomerRequest\x1a\x1a.customer.CustomerResponse\x12G\n" +
	"\vGetCustomer\x12\x1c.customer.GetCustomerRequest\x1a\x1a.customer.CustomerResponse\x12P\n" +
	"\x0eDeleteCustomer\x12\x1f.customer.DeleteCustomerRequest\x1a\x1d.customer.MessageOnlyResponse\x12P\n" +
	"\x0eCreateCustomer\x12\x1f.customer.CreateCustomerRequest\x1a\x1d.customer.MessageOnlyResponse\x12C\n" +
	"\bSendFile\x12\x1a.customer.UploadCSVRequest\x1a\x1b.customer.UploadCSVResponseB\x1eZ\x1ccustomer-service/proto;protob\x06proto3"

var (
	file_customer_service_proto_customer_proto_rawDescOnce sync.Once
	file_customer_service_proto_customer_proto_rawDescData []byte
)

func file_customer_service_proto_customer_proto_rawDescGZIP() []byte {
	file_customer_service_proto_customer_proto_rawDescOnce.Do(func() {
		file_customer_service_proto_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customer_service_proto_customer_proto_rawDesc), len(file_customer_service_proto_customer_proto_rawDesc)))
	})
	return file_customer_service_proto_customer_proto_rawDescData
}

var file_customer_service_proto_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_customer_service_proto_customer_proto_goTypes = []any{
	(*Customer)(nil),              // 0: customer.Customer
	(*CreateCustomerRequest)(nil), // 1: customer.CreateCustomerRequest
	(*EditCustomerRequest)(nil),   // 2: customer.EditCustomerRequest
	(*GetCustomerRequest)(nil),    // 3: customer.GetCustomerRequest
	(*DeleteCustomerRequest)(nil), // 4: customer.DeleteCustomerRequest
	(*CustomerResponse)(nil),      // 5: customer.CustomerResponse
	(*MessageOnlyResponse)(nil),   // 6: customer.MessageOnlyResponse
	(*UploadCSVRequest)(nil),      // 7: customer.UploadCSVRequest
	(*UploadCSVResponse)(nil),     // 8: customer.UploadCSVResponse
}
var file_customer_service_proto_customer_proto_depIdxs = []int32{
	0, // 0: customer.CustomerResponse.customer:type_name -> customer.Customer
	2, // 1: customer.CustomerService.EditCustomer:input_type -> customer.EditCustomerRequest
	3, // 2: customer.CustomerService.GetCustomer:input_type -> customer.GetCustomerRequest
	4, // 3: customer.CustomerService.DeleteCustomer:input_type -> customer.DeleteCustomerRequest
	1, // 4: customer.CustomerService.CreateCustomer:input_type -> customer.CreateCustomerRequest
	7, // 5: customer.CustomerService.SendFile:input_type -> customer.UploadCSVRequest
	5, // 6: customer.CustomerService.EditCustomer:output_type -> customer.CustomerResponse
	5, // 7: customer.CustomerService.GetCustomer:output_type -> customer.CustomerResponse
	6, // 8: customer.CustomerService.DeleteCustomer:output_type -> customer.MessageOnlyResponse
	6, // 9: customer.CustomerService.CreateCustomer:output_type -> customer.MessageOnlyResponse
	8, // 10: customer.CustomerService.SendFile:output_type -> customer.UploadCSVResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_customer_service_proto_customer_proto_init() }
func file_customer_service_proto_customer_proto_init() {
	if File_customer_service_proto_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customer_service_proto_customer_proto_rawDesc), len(file_customer_service_proto_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_customer_service_proto_customer_proto_goTypes,
		DependencyIndexes: file_customer_service_proto_customer_proto_depIdxs,
		MessageInfos:      file_customer_service_proto_customer_proto_msgTypes,
	}.Build()
	File_customer_service_proto_customer_proto = out.File
	file_customer_service_proto_customer_proto_goTypes = nil
	file_customer_service_proto_customer_proto_depIdxs = nil
}
